# Generated by Django 2.2.4 on 2019-09-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'histories'},
        ),
    ]
