# Generated by Django 2.2 on 2019-04-15 05:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.TextField(max_length=100)),
                ('componets', jsonfield.fields.JSONField()),
            ],
        ),
    ]
