# Generated by Django 2.2 on 2019-04-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='componets',
            new_name='components',
        ),
    ]
