# Generated by Django 2.2 on 2019-04-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20190415_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='borrower',
            field=models.CharField(max_length=100),
        ),
    ]
