# Generated by Django 2.2.4 on 2019-08-31 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('ieee_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(null=True)),
                ('component_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.user')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='borrowed_by',
            field=models.ManyToManyField(to='components.user'),
        ),
    ]
